/*
 Data Transfer

 Author		: Hao Yukun
 LU ID		: 37532073
 BJTU ID	: 18722007

 Source File: Chinook.db
 Date: 11/06/2021 02:13:07
*/

PRAGMA foreign_keys = false;

-- ----------------------------
-- Table structure for Album
-- ----------------------------
DROP TABLE IF EXISTS "Album";
CREATE TABLE "Album" (
  "AlbumId" INTEGER,
  "Title" NVARCHAR(160),
  "ArtistId" INTEGER,
  PRIMARY KEY ("AlbumId"),
  FOREIGN KEY ("ArtistId") REFERENCES "Artist" ("ArtistId")
);

-- ----------------------------
-- Records of Album
-- ----------------------------
INSERT INTO "Album" VALUES (1, 'For Those About To Rock We Salute You', 1);
INSERT INTO "Album" VALUES (2, 'Balls to the Wall', 2);
INSERT INTO "Album" VALUES (3, 'Restless and Wild', 2);
INSERT INTO "Album" VALUES (4, 'Let There Be Rock', 1);
INSERT INTO "Album" VALUES (5, 'Big Ones', 3);
INSERT INTO "Album" VALUES (6, 'Jagged Little Pill', 4);
INSERT INTO "Album" VALUES (7, 'Facelift', 5);
INSERT INTO "Album" VALUES (8, 'Warner 25 Anos', 6);
INSERT INTO "Album" VALUES (9, 'Plays Metallica By Four Cellos', 7);
INSERT INTO "Album" VALUES (10, 'Audioslave', 8);
INSERT INTO "Album" VALUES (11, 'Out Of Exile', 8);
INSERT INTO "Album" VALUES (12, 'BackBeat Soundtrack', 9);
INSERT INTO "Album" VALUES (13, 'The Best Of Billy Cobham', 10);
INSERT INTO "Album" VALUES (14, 'Alcohol Fueled Brewtality Live! [Disc 1]', 11);
INSERT INTO "Album" VALUES (15, 'Alcohol Fueled Brewtality Live! [Disc 2]', 11);
INSERT INTO "Album" VALUES (16, 'Black Sabbath', 12);
INSERT INTO "Album" VALUES (17, 'Black Sabbath Vol. 4 (Remaster)', 12);
INSERT INTO "Album" VALUES (18, 'Body Count', 13);
INSERT INTO "Album" VALUES (19, 'Chemical Wedding', 14);
INSERT INTO "Album" VALUES (20, 'The Best Of Buddy Guy - The Millenium Collection', 15);
INSERT INTO "Album" VALUES (21, 'Prenda Minha', 16);
INSERT INTO "Album" VALUES (22, 'Sozinho Remix Ao Vivo', 16);
INSERT INTO "Album" VALUES (23, 'Minha Historia', 17);
INSERT INTO "Album" VALUES (24, 'Afrociberdelia', 18);
INSERT INTO "Album" VALUES (25, 'Da Lama Ao Caos', 18);
INSERT INTO "Album" VALUES (26, 'Acústico MTV [Live]', 19);
INSERT INTO "Album" VALUES (27, 'Cidade Negra - Hits', 19);
INSERT INTO "Album" VALUES (28, 'Na Pista', 20);
INSERT INTO "Album" VALUES (29, 'Axé Bahia 2001', 21);
INSERT INTO "Album" VALUES (30, 'BBC Sessions [Disc 1] [Live]', 22);
INSERT INTO "Album" VALUES (31, 'Bongo Fury', 23);
INSERT INTO "Album" VALUES (32, 'Carnaval 2001', 21);
INSERT INTO "Album" VALUES (33, 'Chill: Brazil (Disc 1)', 24);
INSERT INTO "Album" VALUES (34, 'Chill: Brazil (Disc 2)', 6);
INSERT INTO "Album" VALUES (35, 'Garage Inc. (Disc 1)', 50);
INSERT INTO "Album" VALUES (36, 'Greatest Hits II', 51);
INSERT INTO "Album" VALUES (37, 'Greatest Kiss', 52);
INSERT INTO "Album" VALUES (38, 'Heart of the Night', 53);
INSERT INTO "Album" VALUES (39, 'International Superhits', 54);
INSERT INTO "Album" VALUES (40, 'Into The Light', 55);
INSERT INTO "Album" VALUES (41, 'Meus Momentos', 56);
INSERT INTO "Album" VALUES (42, 'Minha História', 57);
INSERT INTO "Album" VALUES (43, 'MK III The Final Concerts [Disc 1]', 58);
INSERT INTO "Album" VALUES (44, 'Physical Graffiti [Disc 1]', 22);
INSERT INTO "Album" VALUES (45, 'Sambas De Enredo 2001', 21);
INSERT INTO "Album" VALUES (46, 'Supernatural', 59);
INSERT INTO "Album" VALUES (47, 'The Best of Ed Motta', 37);
INSERT INTO "Album" VALUES (48, 'The Essential Miles Davis [Disc 1]', 68);
INSERT INTO "Album" VALUES (49, 'The Essential Miles Davis [Disc 2]', 68);
INSERT INTO "Album" VALUES (50, 'The Final Concerts (Disc 2)', 58);
INSERT INTO "Album" VALUES (51, 'Up An'' Atom', 69);
INSERT INTO "Album" VALUES (52, 'Vinícius De Moraes - Sem Limite', 70);
INSERT INTO "Album" VALUES (53, 'Vozes do MPB', 21);
INSERT INTO "Album" VALUES (54, 'Chronicle, Vol. 1', 76);
INSERT INTO "Album" VALUES (55, 'Chronicle, Vol. 2', 76);
INSERT INTO "Album" VALUES (56, 'Cássia Eller - Coleção Sem Limite [Disc 2]', 77);
INSERT INTO "Album" VALUES (57, 'Cássia Eller - Sem Limite [Disc 1]', 77);
INSERT INTO "Album" VALUES (58, 'Come Taste The Band', 58);
INSERT INTO "Album" VALUES (59, 'Deep Purple In Rock', 58);
INSERT INTO "Album" VALUES (60, 'Fireball', 58);
INSERT INTO "Album" VALUES (61, 'Knocking at Your Back Door: The Best Of Deep Purple in the 80''s', 58);
INSERT INTO "Album" VALUES (62, 'Machine Head', 58);
INSERT INTO "Album" VALUES (63, 'Purpendicular', 58);
INSERT INTO "Album" VALUES (64, 'Slaves And Masters', 58);
INSERT INTO "Album" VALUES (65, 'Stormbringer', 58);
INSERT INTO "Album" VALUES (66, 'The Battle Rages On', 58);
INSERT INTO "Album" VALUES (67, 'Vault: Def Leppard''s Greatest Hits', 78);
INSERT INTO "Album" VALUES (68, 'Outbreak', 79);
INSERT INTO "Album" VALUES (69, 'Djavan Ao Vivo - Vol. 02', 80);
INSERT INTO "Album" VALUES (70, 'Djavan Ao Vivo - Vol. 1', 80);
INSERT INTO "Album" VALUES (71, 'Elis Regina-Minha História', 41);
INSERT INTO "Album" VALUES (72, 'The Cream Of Clapton', 81);
INSERT INTO "Album" VALUES (73, 'Unplugged', 81);
INSERT INTO "Album" VALUES (74, 'Album Of The Year', 82);
INSERT INTO "Album" VALUES (75, 'Angel Dust', 82);
INSERT INTO "Album" VALUES (76, 'King For A Day Fool For A Lifetime', 82);
INSERT INTO "Album" VALUES (77, 'The Real Thing', 82);
INSERT INTO "Album" VALUES (78, 'Deixa Entrar', 83);
INSERT INTO "Album" VALUES (79, 'In Your Honor [Disc 1]', 84);
INSERT INTO "Album" VALUES (80, 'In Your Honor [Disc 2]', 84);
INSERT INTO "Album" VALUES (81, 'One By One', 84);
INSERT INTO "Album" VALUES (82, 'The Colour And The Shape', 84);
INSERT INTO "Album" VALUES (83, 'My Way: The Best Of Frank Sinatra [Disc 1]', 85);
INSERT INTO "Album" VALUES (84, 'Roda De Funk', 86);
INSERT INTO "Album" VALUES (85, 'As Canções de Eu Tu Eles', 27);
INSERT INTO "Album" VALUES (86, 'Quanta Gente Veio Ver (Live)', 27);
INSERT INTO "Album" VALUES (87, 'Quanta Gente Veio ver--Bônus De Carnaval', 27);
INSERT INTO "Album" VALUES (88, 'Faceless', 87);
INSERT INTO "Album" VALUES (89, 'American Idiot', 54);
INSERT INTO "Album" VALUES (90, 'Appetite for Destruction', 88);
INSERT INTO "Album" VALUES (91, 'Use Your Illusion I', 88);
INSERT INTO "Album" VALUES (92, 'Use Your Illusion II', 88);
INSERT INTO "Album" VALUES (93, 'Blue Moods', 89);
INSERT INTO "Album" VALUES (94, 'A Matter of Life and Death', 90);
INSERT INTO "Album" VALUES (95, 'A Real Dead One', 90);
INSERT INTO "Album" VALUES (96, 'A Real Live One', 90);
INSERT INTO "Album" VALUES (97, 'Brave New World', 90);
INSERT INTO "Album" VALUES (98, 'Dance Of Death', 90);
INSERT INTO "Album" VALUES (99, 'Fear Of The Dark', 90);
INSERT INTO "Album" VALUES (100, 'Iron Maiden', 90);
INSERT INTO "Album" VALUES (101, 'Killers', 90);
INSERT INTO "Album" VALUES (102, 'Live After Death', 90);
INSERT INTO "Album" VALUES (103, 'Live At Donington 1992 (Disc 1)', 90);
INSERT INTO "Album" VALUES (104, 'Live At Donington 1992 (Disc 2)', 90);
INSERT INTO "Album" VALUES (105, 'No Prayer For The Dying', 90);
INSERT INTO "Album" VALUES (106, 'Piece Of Mind', 90);
INSERT INTO "Album" VALUES (107, 'Powerslave', 90);
INSERT INTO "Album" VALUES (108, 'Rock In Rio [CD1]', 90);
INSERT INTO "Album" VALUES (109, 'Rock In Rio [CD2]', 90);
INSERT INTO "Album" VALUES (110, 'Seventh Son of a Seventh Son', 90);
INSERT INTO "Album" VALUES (111, 'Somewhere in Time', 90);
INSERT INTO "Album" VALUES (112, 'The Number of The Beast', 90);
INSERT INTO "Album" VALUES (113, 'The X Factor', 90);
INSERT INTO "Album" VALUES (114, 'Virtual XI', 90);
INSERT INTO "Album" VALUES (115, 'Sex Machine', 91);
INSERT INTO "Album" VALUES (116, 'Emergency On Planet Earth', 92);
INSERT INTO "Album" VALUES (117, 'Synkronized', 92);
INSERT INTO "Album" VALUES (118, 'The Return Of The Space Cowboy', 92);
INSERT INTO "Album" VALUES (119, 'Get Born', 93);
INSERT INTO "Album" VALUES (120, 'Are You Experienced?', 94);
INSERT INTO "Album" VALUES (121, 'Surfing with the Alien (Remastered)', 95);
INSERT INTO "Album" VALUES (122, 'Jorge Ben Jor 25 Anos', 46);
INSERT INTO "Album" VALUES (123, 'Jota Quest-1995', 96);
INSERT INTO "Album" VALUES (124, 'Cafezinho', 97);
INSERT INTO "Album" VALUES (125, 'Living After Midnight', 98);
INSERT INTO "Album" VALUES (126, 'Unplugged [Live]', 52);
INSERT INTO "Album" VALUES (127, 'BBC Sessions [Disc 2] [Live]', 22);
INSERT INTO "Album" VALUES (128, 'Coda', 22);
INSERT INTO "Album" VALUES (129, 'Houses Of The Holy', 22);
INSERT INTO "Album" VALUES (130, 'In Through The Out Door', 22);
INSERT INTO "Album" VALUES (131, 'IV', 22);
INSERT INTO "Album" VALUES (132, 'Led Zeppelin I', 22);
INSERT INTO "Album" VALUES (133, 'Led Zeppelin II', 22);
INSERT INTO "Album" VALUES (134, 'Led Zeppelin III', 22);
INSERT INTO "Album" VALUES (135, 'Physical Graffiti [Disc 2]', 22);
INSERT INTO "Album" VALUES (136, 'Presence', 22);
INSERT INTO "Album" VALUES (137, 'The Song Remains The Same (Disc 1)', 22);
INSERT INTO "Album" VALUES (138, 'The Song Remains The Same (Disc 2)', 22);
INSERT INTO "Album" VALUES (139, 'A TempestadeTempestade Ou O Livro Dos Dias', 99);
INSERT INTO "Album" VALUES (140, 'Mais Do Mesmo', 99);
INSERT INTO "Album" VALUES (141, 'Greatest Hits', 100);
INSERT INTO "Album" VALUES (142, 'Lulu Santos - RCA 100 Anos De Música - Álbum 01', 101);
INSERT INTO "Album" VALUES (143, 'Lulu Santos - RCA 100 Anos De Música - Álbum 02', 101);
INSERT INTO "Album" VALUES (144, 'Misplaced Childhood', 102);
INSERT INTO "Album" VALUES (145, 'Barulhinho Bom', 103);
INSERT INTO "Album" VALUES (146, 'Seek And Shall Find: More Of The Best (1963-1981)', 104);
INSERT INTO "Album" VALUES (147, 'The Best Of Men At Work', 105);
INSERT INTO "Album" VALUES (148, 'Black Album', 50);
INSERT INTO "Album" VALUES (149, 'Garage Inc. (Disc 2)', 50);
INSERT INTO "Album" VALUES (150, 'Kill ''Em All', 50);
INSERT INTO "Album" VALUES (151, 'Load', 50);
INSERT INTO "Album" VALUES (152, 'Master Of Puppets', 50);
INSERT INTO "Album" VALUES (153, 'ReLoad', 50);
INSERT INTO "Album" VALUES (154, 'Ride The Lightning', 50);
INSERT INTO "Album" VALUES (155, 'St. Anger', 50);
INSERT INTO "Album" VALUES (156, '...And Justice For All', 50);
INSERT INTO "Album" VALUES (157, 'Miles Ahead', 68);
INSERT INTO "Album" VALUES (158, 'Milton Nascimento Ao Vivo', 42);
INSERT INTO "Album" VALUES (159, 'Minas', 42);
INSERT INTO "Album" VALUES (160, 'Ace Of Spades', 106);
INSERT INTO "Album" VALUES (161, 'Demorou...', 108);
INSERT INTO "Album" VALUES (162, 'Motley Crue Greatest Hits', 109);
INSERT INTO "Album" VALUES (163, 'From The Muddy Banks Of The Wishkah [Live]', 110);
INSERT INTO "Album" VALUES (164, 'Nevermind', 110);
INSERT INTO "Album" VALUES (165, 'Compositores', 111);
INSERT INTO "Album" VALUES (166, 'Olodum', 112);
INSERT INTO "Album" VALUES (167, 'Acústico MTV', 113);
INSERT INTO "Album" VALUES (168, 'Arquivo II', 113);
INSERT INTO "Album" VALUES (169, 'Arquivo Os Paralamas Do Sucesso', 113);
INSERT INTO "Album" VALUES (170, 'Bark at the Moon (Remastered)', 114);
INSERT INTO "Album" VALUES (171, 'Blizzard of Ozz', 114);
INSERT INTO "Album" VALUES (172, 'Diary of a Madman (Remastered)', 114);
INSERT INTO "Album" VALUES (173, 'No More Tears (Remastered)', 114);
INSERT INTO "Album" VALUES (174, 'Tribute', 114);
INSERT INTO "Album" VALUES (175, 'Walking Into Clarksdale', 115);
INSERT INTO "Album" VALUES (176, 'Original Soundtracks 1', 116);
INSERT INTO "Album" VALUES (177, 'The Beast Live', 117);
INSERT INTO "Album" VALUES (178, 'Live On Two Legs [Live]', 118);
INSERT INTO "Album" VALUES (179, 'Pearl Jam', 118);
INSERT INTO "Album" VALUES (180, 'Riot Act', 118);
INSERT INTO "Album" VALUES (181, 'Ten', 118);
INSERT INTO "Album" VALUES (182, 'Vs.', 118);
INSERT INTO "Album" VALUES (183, 'Dark Side Of The Moon', 120);
INSERT INTO "Album" VALUES (184, 'Os Cães Ladram Mas A Caravana Não Pára', 121);
INSERT INTO "Album" VALUES (185, 'Greatest Hits I', 51);
INSERT INTO "Album" VALUES (186, 'News Of The World', 51);
INSERT INTO "Album" VALUES (187, 'Out Of Time', 122);
INSERT INTO "Album" VALUES (188, 'Green', 124);
INSERT INTO "Album" VALUES (189, 'New Adventures In Hi-Fi', 124);
INSERT INTO "Album" VALUES (190, 'The Best Of R.E.M.: The IRS Years', 124);
INSERT INTO "Album" VALUES (191, 'Cesta Básica', 125);
INSERT INTO "Album" VALUES (192, 'Raul Seixas', 126);
INSERT INTO "Album" VALUES (193, 'Blood Sugar Sex Magik', 127);
INSERT INTO "Album" VALUES (194, 'By The Way', 127);
INSERT INTO "Album" VALUES (195, 'Californication', 127);
INSERT INTO "Album" VALUES (196, 'Retrospective I (1974-1980)', 128);
INSERT INTO "Album" VALUES (197, 'Santana - As Years Go By', 59);
INSERT INTO "Album" VALUES (198, 'Santana Live', 59);
INSERT INTO "Album" VALUES (199, 'Maquinarama', 130);
INSERT INTO "Album" VALUES (200, 'O Samba Poconé', 130);
INSERT INTO "Album" VALUES (201, 'Judas 0: B-Sides and Rarities', 131);
INSERT INTO "Album" VALUES (202, 'Rotten Apples: Greatest Hits', 131);
INSERT INTO "Album" VALUES (203, 'A-Sides', 132);
INSERT INTO "Album" VALUES (204, 'Morning Dance', 53);
INSERT INTO "Album" VALUES (205, 'In Step', 133);
INSERT INTO "Album" VALUES (206, 'Core', 134);
INSERT INTO "Album" VALUES (207, 'Mezmerize', 135);
INSERT INTO "Album" VALUES (208, '[1997] Black Light Syndrome', 136);
INSERT INTO "Album" VALUES (209, 'Live [Disc 1]', 137);
INSERT INTO "Album" VALUES (210, 'Live [Disc 2]', 137);
INSERT INTO "Album" VALUES (211, 'The Singles', 138);
INSERT INTO "Album" VALUES (212, 'Beyond Good And Evil', 139);
INSERT INTO "Album" VALUES (213, 'Pure Cult: The Best Of The Cult (For Rockers, Ravers, Lovers & Sinners) [UK]', 139);
INSERT INTO "Album" VALUES (214, 'The Doors', 140);
INSERT INTO "Album" VALUES (215, 'The Police Greatest Hits', 141);
INSERT INTO "Album" VALUES (216, 'Hot Rocks, 1964-1971 (Disc 1)', 142);
INSERT INTO "Album" VALUES (217, 'No Security', 142);
INSERT INTO "Album" VALUES (218, 'Voodoo Lounge', 142);
INSERT INTO "Album" VALUES (219, 'Tangents', 143);
INSERT INTO "Album" VALUES (220, 'Transmission', 143);
INSERT INTO "Album" VALUES (221, 'My Generation - The Very Best Of The Who', 144);
INSERT INTO "Album" VALUES (222, 'Serie Sem Limite (Disc 1)', 145);
INSERT INTO "Album" VALUES (223, 'Serie Sem Limite (Disc 2)', 145);
INSERT INTO "Album" VALUES (224, 'Acústico', 146);
INSERT INTO "Album" VALUES (225, 'Volume Dois', 146);
INSERT INTO "Album" VALUES (226, 'Battlestar Galactica: The Story So Far', 147);
INSERT INTO "Album" VALUES (227, 'Battlestar Galactica, Season 3', 147);
INSERT INTO "Album" VALUES (228, 'Heroes, Season 1', 148);
INSERT INTO "Album" VALUES (229, 'Lost, Season 3', 149);
INSERT INTO "Album" VALUES (230, 'Lost, Season 1', 149);
INSERT INTO "Album" VALUES (231, 'Lost, Season 2', 149);
INSERT INTO "Album" VALUES (232, 'Achtung Baby', 150);
INSERT INTO "Album" VALUES (233, 'All That You Can''t Leave Behind', 150);
INSERT INTO "Album" VALUES (234, 'B-Sides 1980-1990', 150);
INSERT INTO "Album" VALUES (235, 'How To Dismantle An Atomic Bomb', 150);
INSERT INTO "Album" VALUES (236, 'Pop', 150);
INSERT INTO "Album" VALUES (237, 'Rattle And Hum', 150);
INSERT INTO "Album" VALUES (238, 'The Best Of 1980-1990', 150);
INSERT INTO "Album" VALUES (239, 'War', 150);
INSERT INTO "Album" VALUES (240, 'Zooropa', 150);
INSERT INTO "Album" VALUES (241, 'UB40 The Best Of - Volume Two [UK]', 151);
INSERT INTO "Album" VALUES (242, 'Diver Down', 152);
INSERT INTO "Album" VALUES (243, 'The Best Of Van Halen, Vol. I', 152);
INSERT INTO "Album" VALUES (244, 'Van Halen', 152);
INSERT INTO "Album" VALUES (245, 'Van Halen III', 152);
INSERT INTO "Album" VALUES (246, 'Contraband', 153);
INSERT INTO "Album" VALUES (247, 'Vinicius De Moraes', 72);
INSERT INTO "Album" VALUES (248, 'Ao Vivo [IMPORT]', 155);
INSERT INTO "Album" VALUES (249, 'The Office, Season 1', 156);
INSERT INTO "Album" VALUES (250, 'The Office, Season 2', 156);
INSERT INTO "Album" VALUES (251, 'The Office, Season 3', 156);
INSERT INTO "Album" VALUES (252, 'Un-Led-Ed', 157);
INSERT INTO "Album" VALUES (253, 'Battlestar Galactica (Classic), Season 1', 158);
INSERT INTO "Album" VALUES (254, 'Aquaman', 159);
INSERT INTO "Album" VALUES (255, 'Instant Karma: The Amnesty International Campaign to Save Darfur', 150);
INSERT INTO "Album" VALUES (256, 'Speak of the Devil', 114);
INSERT INTO "Album" VALUES (257, '20th Century Masters - The Millennium Collection: The Best of Scorpions', 179);
INSERT INTO "Album" VALUES (258, 'House of Pain', 180);
INSERT INTO "Album" VALUES (259, 'Radio Brasil (O Som da Jovem Vanguarda) - Seleccao de Henrique Amaro', 36);
INSERT INTO "Album" VALUES (260, 'Cake: B-Sides and Rarities', 196);
INSERT INTO "Album" VALUES (261, 'LOST, Season 4', 149);
INSERT INTO "Album" VALUES (262, 'Quiet Songs', 197);
INSERT INTO "Album" VALUES (263, 'Muso Ko', 198);
INSERT INTO "Album" VALUES (264, 'Realize', 199);
INSERT INTO "Album" VALUES (265, 'Every Kind of Light', 200);
INSERT INTO "Album" VALUES (266, 'Duos II', 201);
INSERT INTO "Album" VALUES (267, 'Worlds', 202);
INSERT INTO "Album" VALUES (268, 'The Best of Beethoven', 203);
INSERT INTO "Album" VALUES (269, 'Temple of the Dog', 204);
INSERT INTO "Album" VALUES (270, 'Carry On', 205);
INSERT INTO "Album" VALUES (271, 'Revelations', 8);
INSERT INTO "Album" VALUES (272, 'Adorate Deum: Gregorian Chant from the Proper of the Mass', 206);
INSERT INTO "Album" VALUES (273, 'Allegri: Miserere', 207);
INSERT INTO "Album" VALUES (274, 'Pachelbel: Canon & Gigue', 208);
INSERT INTO "Album" VALUES (275, 'Vivaldi: The Four Seasons', 209);
INSERT INTO "Album" VALUES (276, 'Bach: Violin Concertos', 210);
INSERT INTO "Album" VALUES (277, 'Bach: Goldberg Variations', 211);
INSERT INTO "Album" VALUES (278, 'Bach: The Cello Suites', 212);
INSERT INTO "Album" VALUES (279, 'Handel: The Messiah (Highlights)', 213);
INSERT INTO "Album" VALUES (280, 'The World of Classical Favourites', 214);
INSERT INTO "Album" VALUES (281, 'Sir Neville Marriner: A Celebration', 215);
INSERT INTO "Album" VALUES (282, 'Mozart: Wind Concertos', 216);
INSERT INTO "Album" VALUES (283, 'Haydn: Symphonies 99 - 104', 217);
INSERT INTO "Album" VALUES (284, 'Beethoven: Symhonies Nos. 5 & 6', 218);
INSERT INTO "Album" VALUES (285, 'A Soprano Inspired', 219);
INSERT INTO "Album" VALUES (286, 'Great Opera Choruses', 220);
INSERT INTO "Album" VALUES (287, 'Wagner: Favourite Overtures', 221);
INSERT INTO "Album" VALUES (288, 'Fauré: Requiem, Ravel: Pavane & Others', 222);
INSERT INTO "Album" VALUES (289, 'Tchaikovsky: The Nutcracker', 223);
INSERT INTO "Album" VALUES (290, 'The Last Night of the Proms', 224);
INSERT INTO "Album" VALUES (291, 'Puccini: Madama Butterfly - Highlights', 225);
INSERT INTO "Album" VALUES (292, 'Holst: The Planets, Op. 32 & Vaughan Williams: Fantasies', 226);
INSERT INTO "Album" VALUES (293, 'Pavarotti''s Opera Made Easy', 227);
INSERT INTO "Album" VALUES (294, 'Great Performances - Barber''s Adagio and Other Romantic Favorites for Strings', 228);
INSERT INTO "Album" VALUES (295, 'Carmina Burana', 229);
INSERT INTO "Album" VALUES (296, 'A Copland Celebration, Vol. I', 230);
INSERT INTO "Album" VALUES (297, 'Bach: Toccata & Fugue in D Minor', 231);
INSERT INTO "Album" VALUES (298, 'Prokofiev: Symphony No.1', 232);
INSERT INTO "Album" VALUES (299, 'Scheherazade', 233);
INSERT INTO "Album" VALUES (300, 'Bach: The Brandenburg Concertos', 234);
INSERT INTO "Album" VALUES (301, 'Chopin: Piano Concertos Nos. 1 & 2', 235);
INSERT INTO "Album" VALUES (302, 'Mascagni: Cavalleria Rusticana', 236);
INSERT INTO "Album" VALUES (303, 'Sibelius: Finlandia', 237);
INSERT INTO "Album" VALUES (304, 'Beethoven Piano Sonatas: Moonlight & Pastorale', 238);
INSERT INTO "Album" VALUES (305, 'Great Recordings of the Century - Mahler: Das Lied von der Erde', 240);
INSERT INTO "Album" VALUES (306, 'Elgar: Cello Concerto & Vaughan Williams: Fantasias', 241);
INSERT INTO "Album" VALUES (307, 'Adams, John: The Chairman Dances', 242);
INSERT INTO "Album" VALUES (308, 'Tchaikovsky: 1812 Festival Overture, Op.49, Capriccio Italien & Beethoven: Wellington''s Victory', 243);
INSERT INTO "Album" VALUES (309, 'Palestrina: Missa Papae Marcelli & Allegri: Miserere', 244);
INSERT INTO "Album" VALUES (310, 'Prokofiev: Romeo & Juliet', 245);
INSERT INTO "Album" VALUES (311, 'Strauss: Waltzes', 226);
INSERT INTO "Album" VALUES (312, 'Berlioz: Symphonie Fantastique', 245);
INSERT INTO "Album" VALUES (313, 'Bizet: Carmen Highlights', 246);
INSERT INTO "Album" VALUES (314, 'English Renaissance', 247);
INSERT INTO "Album" VALUES (315, 'Handel: Music for the Royal Fireworks (Original Version 1749)', 208);
INSERT INTO "Album" VALUES (316, 'Grieg: Peer Gynt Suites & Sibelius: Pelléas et Mélisande', 248);
INSERT INTO "Album" VALUES (317, 'Mozart Gala: Famous Arias', 249);
INSERT INTO "Album" VALUES (318, 'SCRIABIN: Vers la flamme', 250);
INSERT INTO "Album" VALUES (319, 'Armada: Music from the Courts of England and Spain', 251);
INSERT INTO "Album" VALUES (320, 'Mozart: Symphonies Nos. 40 & 41', 248);
INSERT INTO "Album" VALUES (321, 'Back to Black', 252);
INSERT INTO "Album" VALUES (322, 'Frank', 252);
INSERT INTO "Album" VALUES (323, 'Carried to Dust (Bonus Track Version)', 253);
INSERT INTO "Album" VALUES (324, 'Beethoven: Symphony No. 6 ''Pastoral'' Etc.', 254);
INSERT INTO "Album" VALUES (325, 'Bartok: Violin & Viola Concertos', 255);
INSERT INTO "Album" VALUES (326, 'Mendelssohn: A Midsummer Night''s Dream', 256);
INSERT INTO "Album" VALUES (327, 'Bach: Orchestral Suites Nos. 1 - 4', 257);
INSERT INTO "Album" VALUES (328, 'Charpentier: Divertissements, Airs & Concerts', 258);
INSERT INTO "Album" VALUES (329, 'South American Getaway', 259);
INSERT INTO "Album" VALUES (330, 'Górecki: Symphony No. 3', 260);
INSERT INTO "Album" VALUES (331, 'Purcell: The Fairy Queen', 261);
INSERT INTO "Album" VALUES (332, 'The Ultimate Relexation Album', 262);
INSERT INTO "Album" VALUES (333, 'Purcell: Music for the Queen Mary', 263);
INSERT INTO "Album" VALUES (334, 'Weill: The Seven Deadly Sins', 264);
INSERT INTO "Album" VALUES (335, 'J.S. Bach: Chaconne, Suite in E Minor, Partita in E Major & Prelude, Fugue and Allegro', 265);
INSERT INTO "Album" VALUES (336, 'Prokofiev: Symphony No.5 & Stravinksy: Le Sacre Du Printemps', 248);
INSERT INTO "Album" VALUES (337, 'Szymanowski: Piano Works, Vol. 1', 266);
INSERT INTO "Album" VALUES (338, 'Nielsen: The Six Symphonies', 267);
INSERT INTO "Album" VALUES (339, 'Great Recordings of the Century: Paganini''s 24 Caprices', 268);
INSERT INTO "Album" VALUES (340, 'Liszt - 12 Études D''Execution Transcendante', 269);
INSERT INTO "Album" VALUES (341, 'Great Recordings of the Century - Shubert: Schwanengesang, 4 Lieder', 270);
INSERT INTO "Album" VALUES (342, 'Locatelli: Concertos for Violin, Strings and Continuo, Vol. 3', 271);
INSERT INTO "Album" VALUES (343, 'Respighi:Pines of Rome', 226);
INSERT INTO "Album" VALUES (344, 'Schubert: The Late String Quartets & String Quintet (3 CD''s)', 272);
INSERT INTO "Album" VALUES (345, 'Monteverdi: L''Orfeo', 273);
INSERT INTO "Album" VALUES (346, 'Mozart: Chamber Music', 274);
INSERT INTO "Album" VALUES (347, 'Koyaanisqatsi (Soundtrack from the Motion Picture)', 275);

-- ----------------------------
-- Table structure for Artist
-- ----------------------------
DROP TABLE IF EXISTS "Artist";
CREATE TABLE "Artist" (
  "ArtistId" INTEGER,
  "Name" NVARCHAR(120),
  PRIMARY KEY ("ArtistId")
);

-- ----------------------------
-- Records of Artist
-- ----------------------------
INSERT INTO "Artist" VALUES (1, 'AC/DC');
INSERT INTO "Artist" VALUES (2, 'Accept');
INSERT INTO "Artist" VALUES (3, 'Aerosmith');
INSERT INTO "Artist" VALUES (4, 'Alanis Morissette');
INSERT INTO "Artist" VALUES (5, 'Alice In Chains');
INSERT INTO "Artist" VALUES (6, 'Antônio Carlos Jobim');
INSERT INTO "Artist" VALUES (7, 'Apocalyptica');
INSERT INTO "Artist" VALUES (8, 'Audioslave');
INSERT INTO "Artist" VALUES (9, 'BackBeat');
INSERT INTO "Artist" VALUES (10, 'Billy Cobham');
INSERT INTO "Artist" VALUES (11, 'Black Label Society');
INSERT INTO "Artist" VALUES (12, 'Black Sabbath');
INSERT INTO "Artist" VALUES (13, 'Body Count');
INSERT INTO "Artist" VALUES (14, 'Bruce Dickinson');
INSERT INTO "Artist" VALUES (15, 'Buddy Guy');
INSERT INTO "Artist" VALUES (16, 'Caetano Veloso');
INSERT INTO "Artist" VALUES (17, 'Chico Buarque');
INSERT INTO "Artist" VALUES (18, 'Chico Science & Nação Zumbi');
INSERT INTO "Artist" VALUES (19, 'Cidade Negra');
INSERT INTO "Artist" VALUES (20, 'Cláudio Zoli');
INSERT INTO "Artist" VALUES (21, 'Various Artists');
INSERT INTO "Artist" VALUES (22, 'Led Zeppelin');
INSERT INTO "Artist" VALUES (23, 'Frank Zappa & Captain Beefheart');
INSERT INTO "Artist" VALUES (24, 'Marcos Valle');
INSERT INTO "Artist" VALUES (25, 'Milton Nascimento & Bebeto');
INSERT INTO "Artist" VALUES (26, 'Azymuth');
INSERT INTO "Artist" VALUES (27, 'Gilberto Gil');
INSERT INTO "Artist" VALUES (28, 'João Gilberto');
INSERT INTO "Artist" VALUES (29, 'Bebel Gilberto');
INSERT INTO "Artist" VALUES (30, 'Jorge Vercilo');
INSERT INTO "Artist" VALUES (31, 'Baby Consuelo');
INSERT INTO "Artist" VALUES (32, 'Ney Matogrosso');
INSERT INTO "Artist" VALUES (33, 'Luiz Melodia');
INSERT INTO "Artist" VALUES (34, 'Nando Reis');
INSERT INTO "Artist" VALUES (35, 'Pedro Luís & A Parede');
INSERT INTO "Artist" VALUES (36, 'O Rappa');
INSERT INTO "Artist" VALUES (37, 'Ed Motta');
INSERT INTO "Artist" VALUES (38, 'Banda Black Rio');
INSERT INTO "Artist" VALUES (39, 'Fernanda Porto');
INSERT INTO "Artist" VALUES (40, 'Os Cariocas');
INSERT INTO "Artist" VALUES (41, 'Elis Regina');
INSERT INTO "Artist" VALUES (42, 'Milton Nascimento');
INSERT INTO "Artist" VALUES (43, 'A Cor Do Som');
INSERT INTO "Artist" VALUES (44, 'Kid Abelha');
INSERT INTO "Artist" VALUES (45, 'Sandra De Sá');
INSERT INTO "Artist" VALUES (46, 'Jorge Ben');
INSERT INTO "Artist" VALUES (47, 'Hermeto Pascoal');
INSERT INTO "Artist" VALUES (48, 'Barão Vermelho');
INSERT INTO "Artist" VALUES (49, 'Edson, DJ Marky & DJ Patife Featuring Fernanda Porto');
INSERT INTO "Artist" VALUES (50, 'Metallica');
INSERT INTO "Artist" VALUES (51, 'Queen');
INSERT INTO "Artist" VALUES (52, 'Kiss');
INSERT INTO "Artist" VALUES (53, 'Spyro Gyra');
INSERT INTO "Artist" VALUES (54, 'Green Day');
INSERT INTO "Artist" VALUES (55, 'David Coverdale');
INSERT INTO "Artist" VALUES (56, 'Gonzaguinha');
INSERT INTO "Artist" VALUES (57, 'Os Mutantes');
INSERT INTO "Artist" VALUES (58, 'Deep Purple');
INSERT INTO "Artist" VALUES (59, 'Santana');
INSERT INTO "Artist" VALUES (60, 'Santana Feat. Dave Matthews');
INSERT INTO "Artist" VALUES (61, 'Santana Feat. Everlast');
INSERT INTO "Artist" VALUES (62, 'Santana Feat. Rob Thomas');
INSERT INTO "Artist" VALUES (63, 'Santana Feat. Lauryn Hill & Cee-Lo');
INSERT INTO "Artist" VALUES (64, 'Santana Feat. The Project G&B');
INSERT INTO "Artist" VALUES (65, 'Santana Feat. Maná');
INSERT INTO "Artist" VALUES (66, 'Santana Feat. Eagle-Eye Cherry');
INSERT INTO "Artist" VALUES (67, 'Santana Feat. Eric Clapton');
INSERT INTO "Artist" VALUES (68, 'Miles Davis');
INSERT INTO "Artist" VALUES (69, 'Gene Krupa');
INSERT INTO "Artist" VALUES (70, 'Toquinho & Vinícius');
INSERT INTO "Artist" VALUES (71, 'Vinícius De Moraes & Baden Powell');
INSERT INTO "Artist" VALUES (72, 'Vinícius De Moraes');
INSERT INTO "Artist" VALUES (73, 'Vinícius E Qurteto Em Cy');
INSERT INTO "Artist" VALUES (74, 'Vinícius E Odette Lara');
INSERT INTO "Artist" VALUES (75, 'Vinicius, Toquinho & Quarteto Em Cy');
INSERT INTO "Artist" VALUES (76, 'Creedence Clearwater Revival');
INSERT INTO "Artist" VALUES (77, 'Cássia Eller');
INSERT INTO "Artist" VALUES (78, 'Def Leppard');
INSERT INTO "Artist" VALUES (79, 'Dennis Chambers');
INSERT INTO "Artist" VALUES (80, 'Djavan');
INSERT INTO "Artist" VALUES (81, 'Eric Clapton');
INSERT INTO "Artist" VALUES (82, 'Faith No More');
INSERT INTO "Artist" VALUES (83, 'Falamansa');
INSERT INTO "Artist" VALUES (84, 'Foo Fighters');
INSERT INTO "Artist" VALUES (85, 'Frank Sinatra');
INSERT INTO "Artist" VALUES (86, 'Funk Como Le Gusta');
INSERT INTO "Artist" VALUES (87, 'Godsmack');
INSERT INTO "Artist" VALUES (88, 'Guns N'' Roses');
INSERT INTO "Artist" VALUES (89, 'Incognito');
INSERT INTO "Artist" VALUES (90, 'Iron Maiden');
INSERT INTO "Artist" VALUES (91, 'James Brown');
INSERT INTO "Artist" VALUES (92, 'Jamiroquai');
INSERT INTO "Artist" VALUES (93, 'JET');
INSERT INTO "Artist" VALUES (94, 'Jimi Hendrix');
INSERT INTO "Artist" VALUES (95, 'Joe Satriani');
INSERT INTO "Artist" VALUES (96, 'Jota Quest');
INSERT INTO "Artist" VALUES (97, 'João Suplicy');
INSERT INTO "Artist" VALUES (98, 'Judas Priest');
INSERT INTO "Artist" VALUES (99, 'Legião Urbana');
INSERT INTO "Artist" VALUES (100, 'Lenny Kravitz');
INSERT INTO "Artist" VALUES (101, 'Lulu Santos');
INSERT INTO "Artist" VALUES (102, 'Marillion');
INSERT INTO "Artist" VALUES (103, 'Marisa Monte');
INSERT INTO "Artist" VALUES (104, 'Marvin Gaye');
INSERT INTO "Artist" VALUES (105, 'Men At Work');
INSERT INTO "Artist" VALUES (106, 'Motörhead');
INSERT INTO "Artist" VALUES (107, 'Motörhead & Girlschool');
INSERT INTO "Artist" VALUES (108, 'Mônica Marianno');
INSERT INTO "Artist" VALUES (109, 'Mötley Crüe');
INSERT INTO "Artist" VALUES (110, 'Nirvana');
INSERT INTO "Artist" VALUES (111, 'O Terço');
INSERT INTO "Artist" VALUES (112, 'Olodum');
INSERT INTO "Artist" VALUES (113, 'Os Paralamas Do Sucesso');
INSERT INTO "Artist" VALUES (114, 'Ozzy Osbourne');
INSERT INTO "Artist" VALUES (115, 'Page & Plant');
INSERT INTO "Artist" VALUES (116, 'Passengers');
INSERT INTO "Artist" VALUES (117, 'Paul D''Ianno');
INSERT INTO "Artist" VALUES (118, 'Pearl Jam');
INSERT INTO "Artist" VALUES (119, 'Peter Tosh');
INSERT INTO "Artist" VALUES (120, 'Pink Floyd');
INSERT INTO "Artist" VALUES (121, 'Planet Hemp');
INSERT INTO "Artist" VALUES (122, 'R.E.M. Feat. Kate Pearson');
INSERT INTO "Artist" VALUES (123, 'R.E.M. Feat. KRS-One');
INSERT INTO "Artist" VALUES (124, 'R.E.M.');
INSERT INTO "Artist" VALUES (125, 'Raimundos');
INSERT INTO "Artist" VALUES (126, 'Raul Seixas');
INSERT INTO "Artist" VALUES (127, 'Red Hot Chili Peppers');
INSERT INTO "Artist" VALUES (128, 'Rush');
INSERT INTO "Artist" VALUES (129, 'Simply Red');
INSERT INTO "Artist" VALUES (130, 'Skank');
INSERT INTO "Artist" VALUES (131, 'Smashing Pumpkins');
INSERT INTO "Artist" VALUES (132, 'Soundgarden');
INSERT INTO "Artist" VALUES (133, 'Stevie Ray Vaughan & Double Trouble');
INSERT INTO "Artist" VALUES (134, 'Stone Temple Pilots');
INSERT INTO "Artist" VALUES (135, 'System Of A Down');
INSERT INTO "Artist" VALUES (136, 'Terry Bozzio, Tony Levin & Steve Stevens');
INSERT INTO "Artist" VALUES (137, 'The Black Crowes');
INSERT INTO "Artist" VALUES (138, 'The Clash');
INSERT INTO "Artist" VALUES (139, 'The Cult');
INSERT INTO "Artist" VALUES (140, 'The Doors');
INSERT INTO "Artist" VALUES (141, 'The Police');
INSERT INTO "Artist" VALUES (142, 'The Rolling Stones');
INSERT INTO "Artist" VALUES (143, 'The Tea Party');
INSERT INTO "Artist" VALUES (144, 'The Who');
INSERT INTO "Artist" VALUES (145, 'Tim Maia');
INSERT INTO "Artist" VALUES (146, 'Titãs');
INSERT INTO "Artist" VALUES (147, 'Battlestar Galactica');
INSERT INTO "Artist" VALUES (148, 'Heroes');
INSERT INTO "Artist" VALUES (149, 'Lost');
INSERT INTO "Artist" VALUES (150, 'U2');
INSERT INTO "Artist" VALUES (151, 'UB40');
INSERT INTO "Artist" VALUES (152, 'Van Halen');
INSERT INTO "Artist" VALUES (153, 'Velvet Revolver');
INSERT INTO "Artist" VALUES (154, 'Whitesnake');
INSERT INTO "Artist" VALUES (155, 'Zeca Pagodinho');
INSERT INTO "Artist" VALUES (156, 'The Office');
INSERT INTO "Artist" VALUES (157, 'Dread Zeppelin');
INSERT INTO "Artist" VALUES (158, 'Battlestar Galactica (Classic)');
INSERT INTO "Artist" VALUES (159, 'Aquaman');
INSERT INTO "Artist" VALUES (160, 'Christina Aguilera featuring BigElf');
INSERT INTO "Artist" VALUES (161, 'Aerosmith & Sierra Leone''s Refugee Allstars');
INSERT INTO "Artist" VALUES (162, 'Los Lonely Boys');
INSERT INTO "Artist" VALUES (163, 'Corinne Bailey Rae');
INSERT INTO "Artist" VALUES (164, 'Dhani Harrison & Jakob Dylan');
INSERT INTO "Artist" VALUES (165, 'Jackson Browne');
INSERT INTO "Artist" VALUES (166, 'Avril Lavigne');
INSERT INTO "Artist" VALUES (167, 'Big & Rich');
INSERT INTO "Artist" VALUES (168, 'Youssou N''Dour');
INSERT INTO "Artist" VALUES (169, 'Black Eyed Peas');
INSERT INTO "Artist" VALUES (170, 'Jack Johnson');
INSERT INTO "Artist" VALUES (171, 'Ben Harper');
INSERT INTO "Artist" VALUES (172, 'Snow Patrol');
INSERT INTO "Artist" VALUES (173, 'Matisyahu');
INSERT INTO "Artist" VALUES (174, 'The Postal Service');
INSERT INTO "Artist" VALUES (175, 'Jaguares');
INSERT INTO "Artist" VALUES (176, 'The Flaming Lips');
INSERT INTO "Artist" VALUES (177, 'Jack''s Mannequin & Mick Fleetwood');
INSERT INTO "Artist" VALUES (178, 'Regina Spektor');
INSERT INTO "Artist" VALUES (179, 'Scorpions');
INSERT INTO "Artist" VALUES (180, 'House Of Pain');
INSERT INTO "Artist" VALUES (181, 'Xis');
INSERT INTO "Artist" VALUES (182, 'Nega Gizza');
INSERT INTO "Artist" VALUES (183, 'Gustavo & Andres Veiga & Salazar');
INSERT INTO "Artist" VALUES (184, 'Rodox');
INSERT INTO "Artist" VALUES (185, 'Charlie Brown Jr.');
INSERT INTO "Artist" VALUES (186, 'Pedro Luís E A Parede');
INSERT INTO "Artist" VALUES (187, 'Los Hermanos');
INSERT INTO "Artist" VALUES (188, 'Mundo Livre S/A');
INSERT INTO "Artist" VALUES (189, 'Otto');
INSERT INTO "Artist" VALUES (190, 'Instituto');
INSERT INTO "Artist" VALUES (191, 'Nação Zumbi');
INSERT INTO "Artist" VALUES (192, 'DJ Dolores & Orchestra Santa Massa');
INSERT INTO "Artist" VALUES (193, 'Seu Jorge');
INSERT INTO "Artist" VALUES (194, 'Sabotage E Instituto');
INSERT INTO "Artist" VALUES (195, 'Stereo Maracana');
INSERT INTO "Artist" VALUES (196, 'Cake');
INSERT INTO "Artist" VALUES (197, 'Aisha Duo');
INSERT INTO "Artist" VALUES (198, 'Habib Koité and Bamada');
INSERT INTO "Artist" VALUES (199, 'Karsh Kale');
INSERT INTO "Artist" VALUES (200, 'The Posies');
INSERT INTO "Artist" VALUES (201, 'Luciana Souza/Romero Lubambo');
INSERT INTO "Artist" VALUES (202, 'Aaron Goldberg');
INSERT INTO "Artist" VALUES (203, 'Nicolaus Esterhazy Sinfonia');
INSERT INTO "Artist" VALUES (204, 'Temple of the Dog');
INSERT INTO "Artist" VALUES (205, 'Chris Cornell');
INSERT INTO "Artist" VALUES (206, 'Alberto Turco & Nova Schola Gregoriana');
INSERT INTO "Artist" VALUES (207, 'Richard Marlow & The Choir of Trinity College, Cambridge');
INSERT INTO "Artist" VALUES (208, 'English Concert & Trevor Pinnock');
INSERT INTO "Artist" VALUES (209, 'Anne-Sophie Mutter, Herbert Von Karajan & Wiener Philharmoniker');
INSERT INTO "Artist" VALUES (210, 'Hilary Hahn, Jeffrey Kahane, Los Angeles Chamber Orchestra & Margaret Batjer');
INSERT INTO "Artist" VALUES (211, 'Wilhelm Kempff');
INSERT INTO "Artist" VALUES (212, 'Yo-Yo Ma');
INSERT INTO "Artist" VALUES (213, 'Scholars Baroque Ensemble');
INSERT INTO "Artist" VALUES (214, 'Academy of St. Martin in the Fields & Sir Neville Marriner');
INSERT INTO "Artist" VALUES (215, 'Academy of St. Martin in the Fields Chamber Ensemble & Sir Neville Marriner');
INSERT INTO "Artist" VALUES (216, 'Berliner Philharmoniker, Claudio Abbado & Sabine Meyer');
INSERT INTO "Artist" VALUES (217, 'Royal Philharmonic Orchestra & Sir Thomas Beecham');
INSERT INTO "Artist" VALUES (218, 'Orchestre Révolutionnaire et Romantique & John Eliot Gardiner');
INSERT INTO "Artist" VALUES (219, 'Britten Sinfonia, Ivor Bolton & Lesley Garrett');
INSERT INTO "Artist" VALUES (220, 'Chicago Symphony Chorus, Chicago Symphony Orchestra & Sir Georg Solti');
INSERT INTO "Artist" VALUES (221, 'Sir Georg Solti & Wiener Philharmoniker');
INSERT INTO "Artist" VALUES (222, 'Academy of St. Martin in the Fields, John Birch, Sir Neville Marriner & Sylvia McNair');
INSERT INTO "Artist" VALUES (223, 'London Symphony Orchestra & Sir Charles Mackerras');
INSERT INTO "Artist" VALUES (224, 'Barry Wordsworth & BBC Concert Orchestra');
INSERT INTO "Artist" VALUES (225, 'Herbert Von Karajan, Mirella Freni & Wiener Philharmoniker');
INSERT INTO "Artist" VALUES (226, 'Eugene Ormandy');
INSERT INTO "Artist" VALUES (227, 'Luciano Pavarotti');
INSERT INTO "Artist" VALUES (228, 'Leonard Bernstein & New York Philharmonic');
INSERT INTO "Artist" VALUES (229, 'Boston Symphony Orchestra & Seiji Ozawa');
INSERT INTO "Artist" VALUES (230, 'Aaron Copland & London Symphony Orchestra');
INSERT INTO "Artist" VALUES (231, 'Ton Koopman');
INSERT INTO "Artist" VALUES (232, 'Sergei Prokofiev & Yuri Temirkanov');
INSERT INTO "Artist" VALUES (233, 'Chicago Symphony Orchestra & Fritz Reiner');
INSERT INTO "Artist" VALUES (234, 'Orchestra of The Age of Enlightenment');
INSERT INTO "Artist" VALUES (235, 'Emanuel Ax, Eugene Ormandy & Philadelphia Orchestra');
INSERT INTO "Artist" VALUES (236, 'James Levine');
INSERT INTO "Artist" VALUES (237, 'Berliner Philharmoniker & Hans Rosbaud');
INSERT INTO "Artist" VALUES (238, 'Maurizio Pollini');
INSERT INTO "Artist" VALUES (239, 'Academy of St. Martin in the Fields, Sir Neville Marriner & William Bennett');
INSERT INTO "Artist" VALUES (240, 'Gustav Mahler');
INSERT INTO "Artist" VALUES (241, 'Felix Schmidt, London Symphony Orchestra & Rafael Frühbeck de Burgos');
INSERT INTO "Artist" VALUES (242, 'Edo de Waart & San Francisco Symphony');
INSERT INTO "Artist" VALUES (243, 'Antal Doráti & London Symphony Orchestra');
INSERT INTO "Artist" VALUES (244, 'Choir Of Westminster Abbey & Simon Preston');
INSERT INTO "Artist" VALUES (245, 'Michael Tilson Thomas & San Francisco Symphony');
INSERT INTO "Artist" VALUES (246, 'Chor der Wiener Staatsoper, Herbert Von Karajan & Wiener Philharmoniker');
INSERT INTO "Artist" VALUES (247, 'The King''s Singers');
INSERT INTO "Artist" VALUES (248, 'Berliner Philharmoniker & Herbert Von Karajan');
INSERT INTO "Artist" VALUES (249, 'Sir Georg Solti, Sumi Jo & Wiener Philharmoniker');
INSERT INTO "Artist" VALUES (250, 'Christopher O''Riley');
INSERT INTO "Artist" VALUES (251, 'Fretwork');
INSERT INTO "Artist" VALUES (252, 'Amy Winehouse');
INSERT INTO "Artist" VALUES (253, 'Calexico');
INSERT INTO "Artist" VALUES (254, 'Otto Klemperer & Philharmonia Orchestra');
INSERT INTO "Artist" VALUES (255, 'Yehudi Menuhin');
INSERT INTO "Artist" VALUES (256, 'Philharmonia Orchestra & Sir Neville Marriner');
INSERT INTO "Artist" VALUES (257, 'Academy of St. Martin in the Fields, Sir Neville Marriner & Thurston Dart');
INSERT INTO "Artist" VALUES (258, 'Les Arts Florissants & William Christie');
INSERT INTO "Artist" VALUES (259, 'The 12 Cellists of The Berlin Philharmonic');
INSERT INTO "Artist" VALUES (260, 'Adrian Leaper & Doreen de Feis');
INSERT INTO "Artist" VALUES (261, 'Roger Norrington, London Classical Players');
INSERT INTO "Artist" VALUES (262, 'Charles Dutoit & L''Orchestre Symphonique de Montréal');
INSERT INTO "Artist" VALUES (263, 'Equale Brass Ensemble, John Eliot Gardiner & Munich Monteverdi Orchestra and Choir');
INSERT INTO "Artist" VALUES (264, 'Kent Nagano and Orchestre de l''Opéra de Lyon');
INSERT INTO "Artist" VALUES (265, 'Julian Bream');
INSERT INTO "Artist" VALUES (266, 'Martin Roscoe');
INSERT INTO "Artist" VALUES (267, 'Göteborgs Symfoniker & Neeme Järvi');
INSERT INTO "Artist" VALUES (268, 'Itzhak Perlman');
INSERT INTO "Artist" VALUES (269, 'Michele Campanella');
INSERT INTO "Artist" VALUES (270, 'Gerald Moore');
INSERT INTO "Artist" VALUES (271, 'Mela Tenenbaum, Pro Musica Prague & Richard Kapp');
INSERT INTO "Artist" VALUES (272, 'Emerson String Quartet');
INSERT INTO "Artist" VALUES (273, 'C. Monteverdi, Nigel Rogers - Chiaroscuro; London Baroque; London Cornett & Sackbu');
INSERT INTO "Artist" VALUES (274, 'Nash Ensemble');
INSERT INTO "Artist" VALUES (275, 'Philip Glass Ensemble');

-- ----------------------------
-- Table structure for Customer
-- ----------------------------
DROP TABLE IF EXISTS "Customer";
CREATE TABLE "Customer" (
  "CustomerId" INTEGER,
  "FirstName" NVARCHAR(40),
  "LastName" NVARCHAR(20),
  "Company" NVARCHAR(80),
  "Address" NVARCHAR(70),
  "City" NVARCHAR(40),
  "State" NVARCHAR(40),
  "Country" NVARCHAR(40),
  "PostalCode" NVARCHAR(10),
  "Phone" NVARCHAR(24),
  "Fax" NVARCHAR(24),
  "Email" NVARCHAR(60),
  "SupportRepId" INTEGER,
  PRIMARY KEY ("CustomerId"),
  FOREIGN KEY ("SupportRepId") REFERENCES "Employee" ("EmployeeId")
);
